### ISSUE TITLE
Feature request: Automatic insertion based on index

### ISSUE THREAD

**Issue by mkoenig3** [bcdev/zappend#54]
Hi Norman,

it would be great if there was a feature to make sure that newly appended data is inserted at the correct index location. For example, it would be cool if new data would be placed correctly along the 'time' dimension.

Thanks,
Marcel

**Comment by forman** [comment]
With the new `append_step` setting (#21) we could calculate the _correct index location_ you are referring to and the update the location (#29) given that we insert empty dummy slices.

If your feature request just concerns the order of slices that are appended in one invocation of zappend, then you could of course sort them on your own before passing the to zappend.

However, if data doesn't have a fixed append step size, but is strictly increasing or decreasing (#20) we could compute an _insert location_, but then all the subsequent steps would have to be shifted by the number of slices inserted. I feel, this is out-of-scope, as this would potentially require very large temporary storage for the rollback operation.

**Comment by mkoenig3** [comment]
Thanks Norman, I agree! Sorting the slices should do for me, too.
