### ISSUE TITLE
Global metadata of target dataset is empty

### ISSUE THREAD

**Issue by TonioF** [bcdev/zappend#56]
I have a collection of zarr files with the same global attributes that I want to combine. After zappend (v 0.4.0) has finished, the file .zattrs at dataset level contains just an empty dictionary {}, the corresponding part in .zmetadata is empty. Metadata of variables looked fine.

My operating system is CentOS, the input zarr files were not consolidated.

**Comment by forman** [comment]
Thanks @TonioF, a blocker, will fix this asap.
